name: .NET Framework app Deploy to IIS

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore webapp

    - name: Build and Publish Web App
      run: msbuild webapp/SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:publishUrl="C:\inetpub\wwwroot\net-wepapp" /p:PackageAsSingleFile=false

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
    #     name: published_webapp
    #     path: bin\Release\Publish